# Site
name: "Blog Artpoint"
title: "Artpoint blog - História, Arte e Viagens"
description: "História, Arte e Viagens"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl:
google_tag_manager: 'GTM-PZ74NF7'
disqus: 'artpoint'
instagram: https://www.instagram.com/joao.artpoint/
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
formspree: https://formspree.io/f/xrgolvjr

# Authors
authors:
  joao:
    name: João Messias
    display_name: João Messias
    #gravatar: e56154546cf4be74e393c62d1ae9f9d4
    avatar: assets/images/joao-messias.jpg
    #email:
    web: https://www.instagram.com/joao.artpoint/
    instagram: https://www.instagram.com/joao.artpoint/
    #twitter:
    description: "Apaixonado por história e arte desde sempre. Idealizador do projeto Artpoint."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/categoria/:name/'

# Pagination 
paginate: 9
paginate_path: /pagina/:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-0000000000000000"
adsense-data-ad-slot: "0000000000"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
